services:
    webbundle.dynamiclayout:
        class: Ast\WebBundle\Lib\DynamicLayout
        arguments: ["@doctrine.orm.entity_manager",'%webbundle.layoutnamespace%']

    webbundle.linksharesocial:
         class: Ast\WebBundle\Lib\LinkShareSocial

    twig.extension.minify:
        class: Ast\WebBundle\Twig\MinifyExtension
        tags:
            - { name: twig.extension }

    assets.empty_version_strategy:
        class: Ast\WebBundle\Asset\VersionStrategy\FileCountVersionStrategy
        arguments: ["%kernel.project_dir%"]
        public: true

    app.listener.compression:
        class: Ast\WebBundle\EventListener\CompressionListener
        arguments:
        tags:
            - { name: kernel.event_subscriber }