<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotationsf3) on 2019-05-29 20:43:53.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Ast\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Ast\WebBundle\Entity\Articulo
 *
 * @ORM\Entity()
 * @ORM\Table(name="WB_Articulos")
 * @ORM\HasLifecycleCallbacks()
 */
class Articulo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $referencia;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $categoriaslug;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $slug;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $categoria;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $titulo;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $subtitulo;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $thumb;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $imagen;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $tags;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    protected $contenido;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    protected $contenidomarkdown;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $publicado= false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fechapublicacion;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $activo= false;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $metaimage;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $metaurlcanonica;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $creado;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $actualizado;

    public function __construct()
    {
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    /**
    * Gets triggered only on insert
    * @ORM\PrePersist
    */
    public function onPrePersist(){
        $this->creado = new \DateTime("now"); 
    }

    /**
    * Gets triggered only on update
    * @ORM\PreUpdate
    */
    public function onPreUpdate(){
        $this->actualizado = new \DateTime("now"); 
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of referencia.
     *
     * @param string $referencia
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setReferencia($referencia)
    {
        $this->referencia = $referencia;

        return $this;
    }

    /**
     * Get the value of referencia.
     *
     * @return string
     */
    public function getReferencia()
    {
        return $this->referencia;
    }

    /**
     * Set the value of categoriaslug.
     *
     * @param string $categoriaslug
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setCategoriaslug($categoriaslug)
    {
        $this->categoriaslug = $categoriaslug;

        return $this;
    }

    /**
     * Get the value of categoriaslug.
     *
     * @return string
     */
    public function getCategoriaslug()
    {
        return $this->categoriaslug;
    }

    /**
     * Set the value of slug.
     *
     * @param string $slug
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of slug.
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set the value of categoria.
     *
     * @param string $categoria
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setCategoria($categoria)
    {
        $this->categoria = $categoria;

        return $this;
    }

    /**
     * Get the value of categoria.
     *
     * @return string
     */
    public function getCategoria()
    {
        return $this->categoria;
    }

    /**
     * Set the value of titulo.
     *
     * @param string $titulo
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setTitulo($titulo)
    {
        $this->titulo = $titulo;

        return $this;
    }

    /**
     * Get the value of titulo.
     *
     * @return string
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * Set the value of subtitulo.
     *
     * @param string $subtitulo
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setSubtitulo($subtitulo)
    {
        $this->subtitulo = $subtitulo;

        return $this;
    }

    /**
     * Get the value of subtitulo.
     *
     * @return string
     */
    public function getSubtitulo()
    {
        return $this->subtitulo;
    }

    /**
     * Set the value of descripcion.
     *
     * @param string $descripcion
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get the value of descripcion.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set the value of thumb.
     *
     * @param string $thumb
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setThumb($thumb)
    {
        $this->thumb = $thumb;

        return $this;
    }

    /**
     * Get the value of thumb.
     *
     * @return string
     */
    public function getThumb()
    {
        return $this->thumb;
    }

    /**
     * Set the value of imagen.
     *
     * @param string $imagen
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get the value of imagen.
     *
     * @return string
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * Set the value of tags.
     *
     * @param string $tags
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get the value of tags.
     *
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set the value of contenido.
     *
     * @param string $contenido
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setContenido($contenido)
    {
        $this->contenido = $contenido;

        return $this;
    }

    /**
     * Get the value of contenido.
     *
     * @return string
     */
    public function getContenido()
    {
        return $this->contenido;
    }

    /**
     * Set the value of contenidomarkdown.
     *
     * @param string $contenidomarkdown
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setContenidomarkdown($contenidomarkdown)
    {
        $this->contenidomarkdown = $contenidomarkdown;

        return $this;
    }

    /**
     * Get the value of contenidomarkdown.
     *
     * @return string
     */
    public function getContenidomarkdown()
    {
        return $this->contenidomarkdown;
    }

    /**
     * Set the value of publicado.
     *
     * @param boolean $publicado
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setPublicado($publicado)
    {
        $this->publicado = $publicado;

        return $this;
    }

    /**
     * Get the value of publicado.
     *
     * @return boolean
     */
    public function getPublicado()
    {
        return $this->publicado;
    }

    /**
     * Set the value of fechapublicacion.
     *
     * @param \DateTime $fechapublicacion
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setFechapublicacion($fechapublicacion)
    {
        $this->fechapublicacion = $fechapublicacion;

        return $this;
    }

    /**
     * Get the value of fechapublicacion.
     *
     * @return \DateTime
     */
    public function getFechapublicacion()
    {
        return $this->fechapublicacion;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of metaimage.
     *
     * @param string $metaimage
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setMetaimage($metaimage)
    {
        $this->metaimage = $metaimage;

        return $this;
    }

    /**
     * Get the value of metaimage.
     *
     * @return string
     */
    public function getMetaimage()
    {
        return $this->metaimage;
    }

    /**
     * Set the value of metaurlcanonica.
     *
     * @param string $metaurlcanonica
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setMetaurlcanonica($metaurlcanonica)
    {
        $this->metaurlcanonica = $metaurlcanonica;

        return $this;
    }

    /**
     * Get the value of metaurlcanonica.
     *
     * @return string
     */
    public function getMetaurlcanonica()
    {
        return $this->metaurlcanonica;
    }

    /**
     * Set the value of creado.
     *
     * @param \DateTime $creado
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setCreado($creado)
    {
        $this->creado = $creado;

        return $this;
    }

    /**
     * Get the value of creado.
     *
     * @return \DateTime
     */
    public function getCreado()
    {
        return $this->creado;
    }

    /**
     * Set the value of actualizado.
     *
     * @param \DateTime $actualizado
     * @return \Ast\WebBundle\Entity\Articulo
     */
    public function setActualizado($actualizado)
    {
        $this->actualizado = $actualizado;

        return $this;
    }

    /**
     * Get the value of actualizado.
     *
     * @return \DateTime
     */
    public function getActualizado()
    {
        return $this->actualizado;
    }

    public function __sleep()
    {
        return array('id', 'referencia', 'categoriaslug', 'slug', 'categoria', 'titulo', 'subtitulo', 'descripcion', 'thumb', 'imagen', 'tags', 'contenido', 'contenidomarkdown', 'publicado', 'fechapublicacion', 'activo', 'metaimage', 'metaurlcanonica', 'creado', 'actualizado');
    }
}