<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotationsf3) on 2019-05-29 20:43:53.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Ast\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Ast\WebBundle\Entity\Boletin
 *
 * @ORM\Entity()
 * @ORM\Table(name="WB_Boletines")
 * @ORM\HasLifecycleCallbacks()
 */
class Boletin
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $correo;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $recibido;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fechacancelado;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $activo= false;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $cancelado= false;

    public function __construct()
    {
    }

    public function __toString()
    {
        return $this->nombre;
    }

    /**
    * Gets triggered only on insert
    * @ORM\PrePersist
    */
    public function onPrePersist(){
        //Cambiar por el campo creado si es que existe en la tabla
        //$this->created = new \DateTime("now"); 
    }

    /**
    * Gets triggered only on update
    * @ORM\PreUpdate
    */
    public function onPreUpdate(){
        //Cambiar por el campo modificado si es que existe en la tabla
        //$this->updated = new \DateTime("now"); 
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of correo.
     *
     * @param string $correo
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setCorreo($correo)
    {
        $this->correo = $correo;

        return $this;
    }

    /**
     * Get the value of correo.
     *
     * @return string
     */
    public function getCorreo()
    {
        return $this->correo;
    }

    /**
     * Set the value of recibido.
     *
     * @param \DateTime $recibido
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setRecibido($recibido)
    {
        $this->recibido = $recibido;

        return $this;
    }

    /**
     * Get the value of recibido.
     *
     * @return \DateTime
     */
    public function getRecibido()
    {
        return $this->recibido;
    }

    /**
     * Set the value of fechacancelado.
     *
     * @param \DateTime $fechacancelado
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setFechacancelado($fechacancelado)
    {
        $this->fechacancelado = $fechacancelado;

        return $this;
    }

    /**
     * Get the value of fechacancelado.
     *
     * @return \DateTime
     */
    public function getFechacancelado()
    {
        return $this->fechacancelado;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of cancelado.
     *
     * @param boolean $cancelado
     * @return \Ast\WebBundle\Entity\Boletin
     */
    public function setCancelado($cancelado)
    {
        $this->cancelado = $cancelado;

        return $this;
    }

    /**
     * Get the value of cancelado.
     *
     * @return boolean
     */
    public function getCancelado()
    {
        return $this->cancelado;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'correo', 'recibido', 'fechacancelado', 'activo', 'cancelado');
    }
}