<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotationsf3) on 2019-05-29 20:43:53.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Ast\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Ast\WebBundle\Entity\Contenido
 *
 * @ORM\Entity()
 * @ORM\Table(name="WB_Contenidos", indexes={@ORM\Index(name="fk_ListaContenido_Lista_idx", columns={"idlista"})})
 * @ORM\HasLifecycleCallbacks()
 */
class Contenido
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $idlista;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $foto;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $titulo;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    protected $contenido;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    protected $orden;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $activo= false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $creado;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $incluirmedia= false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $idmedia;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $incluirgaleria= false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $idgaleria;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $actualizado;

    /**
     * @ORM\ManyToOne(targetEntity="Lista", inversedBy="contenidos")
     * @ORM\JoinColumn(name="idlista", referencedColumnName="id")
     */
    protected $lista;

    public function __construct()
    {
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    /**
    * Gets triggered only on insert
    * @ORM\PrePersist
    */
    public function onPrePersist(){
        $this->creado = new \DateTime("now"); 
    }

    /**
    * Gets triggered only on update
    * @ORM\PreUpdate
    */
    public function onPreUpdate(){
        $this->actualizado = new \DateTime("now"); 
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of idlista.
     *
     * @param integer $idlista
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setIdlista($idlista)
    {
        $this->idlista = $idlista;

        return $this;
    }

    /**
     * Get the value of idlista.
     *
     * @return integer
     */
    public function getIdlista()
    {
        return $this->idlista;
    }

    /**
     * Set the value of foto.
     *
     * @param string $foto
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setFoto($foto)
    {
        $this->foto = $foto;

        return $this;
    }

    /**
     * Get the value of foto.
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->foto;
    }

    /**
     * Set the value of titulo.
     *
     * @param string $titulo
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setTitulo($titulo)
    {
        $this->titulo = $titulo;

        return $this;
    }

    /**
     * Get the value of titulo.
     *
     * @return string
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * Set the value of descripcion.
     *
     * @param string $descripcion
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get the value of descripcion.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set the value of contenido.
     *
     * @param string $contenido
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setContenido($contenido)
    {
        $this->contenido = $contenido;

        return $this;
    }

    /**
     * Get the value of contenido.
     *
     * @return string
     */
    public function getContenido()
    {
        return $this->contenido;
    }

    /**
     * Set the value of orden.
     *
     * @param integer $orden
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setOrden($orden)
    {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get the value of orden.
     *
     * @return integer
     */
    public function getOrden()
    {
        return $this->orden;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of creado.
     *
     * @param \DateTime $creado
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setCreado($creado)
    {
        $this->creado = $creado;

        return $this;
    }

    /**
     * Get the value of creado.
     *
     * @return \DateTime
     */
    public function getCreado()
    {
        return $this->creado;
    }

    /**
     * Set the value of incluirmedia.
     *
     * @param boolean $incluirmedia
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setIncluirmedia($incluirmedia)
    {
        $this->incluirmedia = $incluirmedia;

        return $this;
    }

    /**
     * Get the value of incluirmedia.
     *
     * @return boolean
     */
    public function getIncluirmedia()
    {
        return $this->incluirmedia;
    }

    /**
     * Set the value of idmedia.
     *
     * @param integer $idmedia
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setIdmedia($idmedia)
    {
        $this->idmedia = $idmedia;

        return $this;
    }

    /**
     * Get the value of idmedia.
     *
     * @return integer
     */
    public function getIdmedia()
    {
        return $this->idmedia;
    }

    /**
     * Set the value of incluirgaleria.
     *
     * @param boolean $incluirgaleria
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setIncluirgaleria($incluirgaleria)
    {
        $this->incluirgaleria = $incluirgaleria;

        return $this;
    }

    /**
     * Get the value of incluirgaleria.
     *
     * @return boolean
     */
    public function getIncluirgaleria()
    {
        return $this->incluirgaleria;
    }

    /**
     * Set the value of idgaleria.
     *
     * @param integer $idgaleria
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setIdgaleria($idgaleria)
    {
        $this->idgaleria = $idgaleria;

        return $this;
    }

    /**
     * Get the value of idgaleria.
     *
     * @return integer
     */
    public function getIdgaleria()
    {
        return $this->idgaleria;
    }

    /**
     * Set the value of actualizado.
     *
     * @param \DateTime $actualizado
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setActualizado($actualizado)
    {
        $this->actualizado = $actualizado;

        return $this;
    }

    /**
     * Get the value of actualizado.
     *
     * @return \DateTime
     */
    public function getActualizado()
    {
        return $this->actualizado;
    }

    /**
     * Set Lista entity (many to one).
     *
     * @param \Ast\WebBundle\Entity\Lista $lista
     * @return \Ast\WebBundle\Entity\Contenido
     */
    public function setLista(Lista $lista = null)
    {
        $this->lista = $lista;

        return $this;
    }

    /**
     * Get Lista entity (many to one).
     *
     * @return \Ast\WebBundle\Entity\Lista
     */
    public function getLista()
    {
        return $this->lista;
    }

    public function __sleep()
    {
        return array('id', 'idlista', 'foto', 'titulo', 'descripcion', 'contenido', 'orden', 'activo', 'creado', 'incluirmedia', 'idmedia', 'incluirgaleria', 'idgaleria', 'actualizado');
    }
}