<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotationsf3) on 2019-05-29 20:43:53.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Ast\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Ast\WebBundle\Entity\Equipo
 *
 * @ORM\Entity()
 * @ORM\Table(name="WB_Equipos")
 * @ORM\HasLifecycleCallbacks()
 */
class Equipo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $foto;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $thumb;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $puesto;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $bio;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $nota;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $correo;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $sitioweb;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $twitter;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $linkedin;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $instagram;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $facebook;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $blog;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default":0})
     */
    protected $activo= false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $creado;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $actualizado;

    public function __construct()
    {
    }

    public function __toString()
    {
        return $this->nombre;
    }

    /**
    * Gets triggered only on insert
    * @ORM\PrePersist
    */
    public function onPrePersist(){
        $this->creado = new \DateTime("now"); 
    }

    /**
    * Gets triggered only on update
    * @ORM\PreUpdate
    */
    public function onPreUpdate(){
        $this->actualizado = new \DateTime("now"); 
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of foto.
     *
     * @param string $foto
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setFoto($foto)
    {
        $this->foto = $foto;

        return $this;
    }

    /**
     * Get the value of foto.
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->foto;
    }

    /**
     * Set the value of thumb.
     *
     * @param string $thumb
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setThumb($thumb)
    {
        $this->thumb = $thumb;

        return $this;
    }

    /**
     * Get the value of thumb.
     *
     * @return string
     */
    public function getThumb()
    {
        return $this->thumb;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of puesto.
     *
     * @param string $puesto
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setPuesto($puesto)
    {
        $this->puesto = $puesto;

        return $this;
    }

    /**
     * Get the value of puesto.
     *
     * @return string
     */
    public function getPuesto()
    {
        return $this->puesto;
    }

    /**
     * Set the value of bio.
     *
     * @param string $bio
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setBio($bio)
    {
        $this->bio = $bio;

        return $this;
    }

    /**
     * Get the value of bio.
     *
     * @return string
     */
    public function getBio()
    {
        return $this->bio;
    }

    /**
     * Set the value of nota.
     *
     * @param string $nota
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setNota($nota)
    {
        $this->nota = $nota;

        return $this;
    }

    /**
     * Get the value of nota.
     *
     * @return string
     */
    public function getNota()
    {
        return $this->nota;
    }

    /**
     * Set the value of correo.
     *
     * @param string $correo
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setCorreo($correo)
    {
        $this->correo = $correo;

        return $this;
    }

    /**
     * Get the value of correo.
     *
     * @return string
     */
    public function getCorreo()
    {
        return $this->correo;
    }

    /**
     * Set the value of sitioweb.
     *
     * @param string $sitioweb
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setSitioweb($sitioweb)
    {
        $this->sitioweb = $sitioweb;

        return $this;
    }

    /**
     * Get the value of sitioweb.
     *
     * @return string
     */
    public function getSitioweb()
    {
        return $this->sitioweb;
    }

    /**
     * Set the value of twitter.
     *
     * @param string $twitter
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;

        return $this;
    }

    /**
     * Get the value of twitter.
     *
     * @return string
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Set the value of linkedin.
     *
     * @param string $linkedin
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setLinkedin($linkedin)
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    /**
     * Get the value of linkedin.
     *
     * @return string
     */
    public function getLinkedin()
    {
        return $this->linkedin;
    }

    /**
     * Set the value of instagram.
     *
     * @param string $instagram
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setInstagram($instagram)
    {
        $this->instagram = $instagram;

        return $this;
    }

    /**
     * Get the value of instagram.
     *
     * @return string
     */
    public function getInstagram()
    {
        return $this->instagram;
    }

    /**
     * Set the value of facebook.
     *
     * @param string $facebook
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setFacebook($facebook)
    {
        $this->facebook = $facebook;

        return $this;
    }

    /**
     * Get the value of facebook.
     *
     * @return string
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    /**
     * Set the value of blog.
     *
     * @param string $blog
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setBlog($blog)
    {
        $this->blog = $blog;

        return $this;
    }

    /**
     * Get the value of blog.
     *
     * @return string
     */
    public function getBlog()
    {
        return $this->blog;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of creado.
     *
     * @param \DateTime $creado
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setCreado($creado)
    {
        $this->creado = $creado;

        return $this;
    }

    /**
     * Get the value of creado.
     *
     * @return \DateTime
     */
    public function getCreado()
    {
        return $this->creado;
    }

    /**
     * Set the value of actualizado.
     *
     * @param \DateTime $actualizado
     * @return \Ast\WebBundle\Entity\Equipo
     */
    public function setActualizado($actualizado)
    {
        $this->actualizado = $actualizado;

        return $this;
    }

    /**
     * Get the value of actualizado.
     *
     * @return \DateTime
     */
    public function getActualizado()
    {
        return $this->actualizado;
    }

    public function __sleep()
    {
        return array('id', 'foto', 'thumb', 'nombre', 'puesto', 'bio', 'nota', 'correo', 'sitioweb', 'twitter', 'linkedin', 'instagram', 'facebook', 'blog', 'activo', 'creado', 'actualizado');
    }
}